### PR TITLE
refactor!: un-alias strings in anonymous nodes

### PR DESCRIPTION
**Pull request by amaanq**
# Problem

When viewing or using a parse tree of a query file in the parser's current state, all strings in an anonymous node are aliased to an identifier, thus making it seem like it's an identifier, when it's actually a string. It does not make much sense to alias them here since they are not identifiers, they are strings that represent a literal node rather than a named node in the queries

# Solution

Un-alias strings to identifiers in anonymous nodes

### CODE REVIEW

**Comment by clason** [comment]
Can you check whether this will affect https://github.com/neovim/neovim/blob/2c6b6358722b2df9160c3739b0cea07e8779513f/runtime/lua/vim/treesitter/_query_linter.lua#L66-L78

**Comment by clason** [comment]
@lucario387

**Comment by lucario387** [comment]
I'm ok with this.

**Review by clason — APPROVED** [review]

**Comment by clason** [comment]
Merged. I will _not_ merge #39 (at this time), so go ahead with the nvim-treesitter PR @amaanq

**Review by phattai6883 — COMMENTED** [review]
Vientrang93

**Pull request merged**
