### PR TITLE
fix: properly handle supertypes

### PR DESCRIPTION
**Pull request by amaanq**

### CODE REVIEW

**Comment by clason** [comment]
Did you test this with the query formatter and linter?

**Comment by amaanq** [comment]
nope, not sure how

**Comment by clason** [comment]
This inflates state count quite a bit, though...

> nope, not sure how

Manually build the parser, put it in `.local/share/nvim/site/parser`, then open the Haskell query with Neovim.

**Comment by clason** [comment]
Seems to work as well. I do worry about state count, though.

**Comment by clason** [comment]
Also, this will break queries, which expect `name: (identifier)`.

**Comment by amaanq** [comment]
> Seems to work as well. I do worry about state count, though. Maybe try moving the `seq` into a separate hidden rule?

This increases it by 30



> Also, this will break queries, which expect `name: (identifier)`?

No, unless it's anchored, since the name field is present in both places

**Comment by lucario387** [comment]
This should not break the formatter, at least from what I can see. Running `format-queries runtime/queries` in the haskell PR results in 0diff with the result of latest nvim-treesitter

**Comment by clason** [comment]
@amaanq Do we want to add queries for this?

**Pull request merged**
