### PR TITLE
fix: disallow empty groupings

### PR DESCRIPTION
**Pull request by ribru17**
Something like `()` is a syntax error and it would be nice if the parser reflected that (even if just with a "missing" node rather than an error node).

`ts g` ran with 0.24.3

### CODE REVIEW

**Comment by clason** [comment]
> ts g ran with 0.24.3

Then you need to `git add` the new tree-sitter.json.

**Comment by ObserverOfTime** [comment]
See #42

**Comment by ribru17** [comment]
Yeah I'll just wait for that one to merge then rebase

**Review by amaanq — APPROVED** [review]

**Comment by clason** [comment]
> Something like () is a syntax error and it would be nice if the parser reflected that

For the record, that goes against the general policy that tree-sitter parsers should not try to be linters. (And the breakage in nvim-treesitter shows why...)

**Pull request merged**
